### ISSUE TITLE
Unsupported Command

### ISSUE THREAD

**Issue by Beyondem** [ludoo/ludobot#1]
Can the unsupported command reply be removed?

It gets very annoying when there are multiple bots in the group and LudoBot replies to every one saying Unsupported command.

**Comment by ludoo** [comment]
Done, thanks for reporting it! I never thought about this use case, and am actually glad someone is using this. :)

**Comment by Beyondem** [comment]
Very handy for sharing quotes with people, they get a nice overview right away!
